Repository LITO-apps/Treevel-client, pull requests merged in 2018-07, with the labels that each got.

#1 Feature/create bullet
  Assets/Prefabs.meta
  Assets/Prefabs/normalBulletPrefab.prefab
  Assets/Prefabs/normalBulletPrefab.prefab.meta
  Assets/Scenes/GamePlayScene.unity
  Assets/Scripts/Bullet.meta
  Assets/Scripts/Bullet/BulletController.cs
  Assets/Scripts/Bullet/BulletController.cs.meta
  Assets/Scripts/Bullet/BulletGenerator.cs
  Assets/Scripts/Bullet/BulletGenerator.cs.meta
  Assets/Scripts/Bullet/NormalBulletController.cs
  Assets/Scripts/Bullet/NormalBulletController.cs.meta
  Assets/Textures.meta
  Assets/Textures/normalBullet.png
  Assets/Textures/normalBullet.png.meta
  Assets/Textures/normalBulletWarning.png
  Assets/Textures/normalBulletWarning.png.meta
Labels: enhancement, waiting for review

#2 Feature/create tile
  Assets/Prefabs/NormalTile.prefab
  Assets/Prefabs/NormalTile.prefab.meta
  Assets/Scenes/GamePlayScene.unity
  Assets/Scripts/Data.cs
  Assets/Scripts/Tile.meta
  Assets/Scripts/Tile/TileGenerator.cs
  Assets/Scripts/Tile/TileGenerator.cs.meta
  Assets/Textures/NormalTile.png
  Assets/Textures/NormalTile.png.meta
Labels: enhancement, waiting for review

#3 Modify object in game play scene
  Assets/Prefabs/normalTilePrefab.prefab
  Assets/Prefabs/normalTilePrefab.prefab.meta
  Assets/Scenes/GamePlayScene.unity
Labels: modification, waiting for review

#4 Feature/move bullet
  Assets/Scripts/Bullet/BulletController.cs
  Assets/Scripts/Bullet/BulletGenerator.cs
  Assets/Scripts/Bullet/CartridgeController.cs
  Assets/Scripts/Bullet/CartridgeController.cs.meta
  Assets/Scripts/Bullet/NormalBulletController.cs
Labels: enhancement, waiting for review

#5 Configure code style
  .editorconfig
  .gitignore
  Assets/Prefabs/normalTilePrefab.prefab
  Assets/Prefabs/normalTilePrefab.prefab.meta
  Assets/Scenes/GamePlayScene.unity
  Assets/Scripts/Bullet/BulletController.cs
  Assets/Scripts/Bullet/BulletGenerator.cs
  Assets/Scripts/Bullet/CartridgeController.cs
  Assets/Scripts/Bullet/NormalBulletController.cs
  Assets/Scripts/Data.cs
  Assets/Scripts/Directors/GamePlayDirector.cs
  Assets/Scripts/Tile/TileGenerator.cs
  Assets/Textures/normalTile.png
  Assets/Textures/normalTile.png.meta
  docs/manual.md
Labels: refactoring, waiting for review

#6 Feature/destroy bullet
  Assets/Scripts/Bullet/CartridgeController.cs
  Assets/Scripts/Bullet/NormalBulletController.cs
Labels: enhancement, waiting for review

#7 Feature/create panel
  Assets/Prefabs/normalPanelPrefab.prefab
  Assets/Prefabs/normalPanelPrefab.prefab.meta
  Assets/Scenes/GamePlayScene.unity
  Assets/Scripts/Data.cs
  Assets/Scripts/Panel.meta
  Assets/Scripts/Panel/PanelGenerator.cs
  Assets/Scripts/Panel/PanelGenerator.cs.meta
  Assets/Scripts/Tile/TileGenerator.cs
  Assets/Textures/normalPanel.png
  Assets/Textures/normalPanel.png.meta
Labels: enhancement, waiting for review
