Repository LITO-apps/Treevel-client, pull requests merged in 2018-11, with the labels that each got.

#19 画面の回転を制限する
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#20 ゲームプレイ中にアプリを閉じた時の処理
  Assets/Scenes/GamePlayScene.unity
  Assets/Scripts/Directors/GamePlayDirector.cs
Labels: enhancement

#21 パネルの移動完了前にフリック検知をしてしまう
  Assets/Scripts/GamePlayScene/Panel/NormalPanelController.cs
Labels: bug, waiting for review

#22 1つのステージを作り上げる
  Assets/Scripts/Data.cs
  Assets/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Scripts/GamePlayScene/Bullet/NormalBulletController.cs
  Assets/Scripts/GamePlayScene/Panel/NormalPanelController.cs
  Assets/Scripts/GamePlayScene/Warning/NormalBulletWarningController.cs
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/GraphicsSettings.asset
Labels: enhancement, waiting for review

#23 コード整理
  .editorconfig
  Assets/Scripts/Data.cs
  Assets/Scripts/Directors/GamePlayDirector.cs
  Assets/Scripts/Directors/StageSelectDirector.cs
  Assets/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Scripts/GamePlayScene/Bullet/CartridgeController.cs
  Assets/Scripts/GamePlayScene/Bullet/NormalBulletController.cs
  Assets/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs.meta
  Assets/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Scripts/GamePlayScene/GamePlayDirector.cs.meta
  Assets/Scripts/GamePlayScene/Panel/NormalPanelController.cs
  Assets/Scripts/GamePlayScene/Panel/PanelController.cs
  Assets/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Scripts/GamePlayScene/Tile/TileController.cs
  Assets/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Scripts/GamePlayScene/Warning/BulletWarningController.cs
  Assets/Scripts/GamePlayScene/Warning/BulletWarningController.cs.meta
  Assets/Scripts/GamePlayScene/Warning/CartridgeWarningController.cs
  Assets/Scripts/GamePlayScene/Warning/NormalBulletWarningController.cs
  Assets/Scripts/GamePlayScene/Warning/NormalCartridgeWarningController.cs
  Assets/Scripts/GamePlayScene/Warning/NormalCartridgeWarningController.cs.meta
  Assets/Scripts/GamePlayScene/Warning/WarningController.cs
  Assets/Scripts/StageSelectScene.meta
  Assets/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Scripts/StageSelectScene/StageSelectDirector.cs.meta
Labels: refactoring, waiting for review

#26 多様性の実装① - ディスプレイの比を統一する
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/StageSelectScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Textures/GamePlayScene/background.png
  Assets/Project/Textures/GamePlayScene/background.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement, waiting for review
