Repository LITO-apps/Treevel-client, pull requests merged in 2019-07, with the labels that each got.

#67 ゲーム中にバックグラウンドに移動した旨が表示され続けるバグの改善
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
Labels: bug

#68 撃ち抜く銃弾がダミーパネルを撃ち抜いた時にゲーム失敗となる問題の改善
  Assets/Project/Scenes/GamePlayScene_Profiles.meta
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
Labels: bug

#69 Unity のアップグレード
  Assets/Project/Scripts/LevelSelectScene/LevelSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/csc.rsp
  Assets/csc.rsp.meta
  Packages/manifest.json
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/VFXManager.asset
  ProjectSettings/XRSettings.asset
  README.md
Labels: enhancement

#136 SnapScrollView 内の共通オブジェクトを Prefab 化して管理する
  Assets/Project/Prefabs/RecordScene/levelContents.prefab
  Assets/Project/Prefabs/RecordScene/levelContents.prefab.meta
  Assets/Project/Scenes/RecordScene.unity
Labels: improvement

#132 auto format
  .astylerc
  .editorconfig
  .githooks/pre-commit
  README.md
  tool/astyle/mac/bin/AStyle
  tool/astyle/mac/obj/ASBeautifier.o
  tool/astyle/mac/obj/ASEnhancer.o
  tool/astyle/mac/obj/ASFormatter.o
  tool/astyle/mac/obj/ASLocalizer.o
  tool/astyle/mac/obj/ASResource.o
  tool/astyle/mac/obj/astyle_main.o
Labels: improvement

#135 VSCodeで生成されるファイルをgit管理しない
  .gitignore
Labels: refactoring

#133 ゲームリトライ時にBulletGroupGenerator の初期化処理を記述する
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
Labels: improvement

#128 Singleton Pattern
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/Utils/Patterns.meta
  Assets/Project/Scripts/Utils/Patterns/Singleton.cs
  Assets/Project/Scripts/Utils/Patterns/Singleton.cs.meta
  Assets/Project/Scripts/Utils/Patterns/SingletonObject.cs
  Assets/Project/Scripts/Utils/Patterns/SingletonObject.cs.meta
  README.md
Labels: improvement
