Repository LITO-apps/Treevel-client, pull requests merged in 2019-09, with the labels that each got.

#166 警告画像の表示時間を秒ではなくフレームで管理する
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/BulletWarningController.cs
  Assets/Project/Scripts/Utils/Definitions/BulletWarningDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/BulletWarningDefinitions.cs.meta
Labels: improvement

#171 パネル Prefab において，RequireComponent を使う
  Assets/Project/Prefabs/GamePlayScene/Panel/dynamicDummyPanelPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel1Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel2Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel3Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel4Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel5Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel6Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel7Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanel8Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel1Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel2Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel3Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel4Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel5Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel6Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel7Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel8Prefab.prefab
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/LifeNumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  README.md
Labels: refactoring

#167 撃ち抜く銃弾をBoxCollider2Dを用いた実装に変更する
  Assets/Project/Prefabs/GamePlayScene/Bullet/Cartridge/NormalCartridgePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Cartridge/TurnCartridgePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Hole/NormalHolePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Hole/aimingHolePrefab.prefab
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/LifeNumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
Labels: improvement

#168 重複したスクロールビューを両方動作可能にする
  Assets/Project/Prefabs/StageSelectScene/levelContents.prefab
  Assets/Project/Scripts/StageSelectScene/OverlappedScrollRect.meta
  Assets/Project/Scripts/StageSelectScene/OverlappedScrollRect/FindInterface.cs
  Assets/Project/Scripts/StageSelectScene/OverlappedScrollRect/FindInterface.cs.meta
  Assets/Project/Scripts/StageSelectScene/OverlappedScrollRect/OverlappedScrollRect.cs
  Assets/Project/Scripts/StageSelectScene/OverlappedScrollRect/OverlappedScrollRect.cs.meta
Labels: enhancement

#173 WIP: Third Party のライセンスを追加
  Assets/ThirdParties/SnapScroll/LICENSE.txt
  Assets/ThirdParties/SnapScroll/LICENSE.txt.meta
  Assets/ThirdParties/TouchScript/Editor/TouchManagerEditor.cs
  Assets/ThirdParties/TouchScript/Scripts/Devices/Display/GenericDisplayDevice.cs
Labels: improvement

#176 撃ち抜く銃弾の銃跡をパネルに追従させる
  Assets/Project/Prefabs/GamePlayScene/Bullet/Cartridge/NormalCartridgePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Cartridge/TurnCartridgePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Hole/NormalHolePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Hole/aimingHolePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/dynamicDummyPanelPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/staticDummyPanelPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/normalTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile1Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile2Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile3Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile4Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile5Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile6Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile7Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTile8Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/warpTilePrefab.prefab
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: enhancement

#175 言葉を全て多言語に対応させる
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/ConfigScene.unity
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/RecordScene.unity
  Assets/Project/Scenes/StageSelectScene.unity
  Assets/Project/Scenes/TutorialScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
Labels: enhancement
