Repository LITO-apps/Treevel-client, pull requests merged in 2019-03, with the labels that each got.

#41 銃弾を生成順に描画する
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
Labels: bug, waiting for review

#43 遷移を使わず，ゲームのリトライを行う
  Assets/Project/Prefabs/GamePlayScene/Tile/normalTilePrefab.prefab
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  ProjectSettings/TagManager.asset
Labels: enhancement

#44 警告の表示後に銃弾を生成する
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/CartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/HoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/HoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalCartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalHoleWarningController.cs
  Assets/Project/Scripts/MenuBarScene/MenuBarDirector.cs
Labels: modification, waiting for review

#45 StageGeneratorの導入
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs.meta
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
Labels: enhancement, waiting for review
