Repository LITO-apps/Treevel-client, pull requests merged in 2019-12, with the labels that each got.

#196 LevelSelectSceneを実装
  Assets/Project/Prefabs/LevelSelectScene.meta
  Assets/Project/Prefabs/LevelSelectScene/LevelTree.prefab
  Assets/Project/Prefabs/LevelSelectScene/LevelTree.prefab.meta
  Assets/Project/Scenes/ConfigScene.unity
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/LevelSelectScene.unity
  Assets/Project/Scenes/LevelSelectScene.unity.meta
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/LevelSelectScene.meta
  Assets/Project/Scripts/LevelSelectScene/LevelTreeController.cs
  Assets/Project/Scripts/LevelSelectScene/LevelTreeController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs
  Assets/Project/Scripts/MenuSelectScene/TransitionSelfToggle.cs
  Assets/Project/Scripts/MenuSelectScene/TransitionSelfToggle.cs.meta
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/LevelDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs.meta
  Assets/Project/Textures/LevelSelectScene.meta
  Assets/Project/Textures/LevelSelectScene/tree1.png
  Assets/Project/Textures/LevelSelectScene/tree1.png.meta
  Assets/Project/Textures/LevelSelectScene/tree2.png
  Assets/Project/Textures/LevelSelectScene/tree2.png.meta
  Assets/Project/Textures/LevelSelectScene/tree3.png
  Assets/Project/Textures/LevelSelectScene/tree3.png.meta
  Assets/Project/Textures/LevelSelectScene/tree4.png
  Assets/Project/Textures/LevelSelectScene/tree4.png.meta
  Assets/Project/Textures/LevelSelectScene/tree5.png
  Assets/Project/Textures/LevelSelectScene/tree5.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#225 GUI におけるタイルの実装
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/numberTilePrefab.prefab.meta
  Assets/Project/Resources/GameDatas/Stages/1_1.asset
  Assets/Project/Resources/GameDatas/Stages/1_2.asset
  Assets/Project/Resources/GameDatas/Stages/1_3.asset
  Assets/Project/Resources/GameDatas/Stages/1_7.asset
  Assets/Project/Resources/GameDatas/Stages/2_4.asset
  Assets/Project/Resources/GameDatas/Stages/2_5.asset
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/GameDatas/BulletData.cs
  Assets/Project/Scripts/GameDatas/BulletGroupData.cs
  Assets/Project/Scripts/GameDatas/PanelData.cs
  Assets/Project/Scripts/GameDatas/StageData.cs
  Assets/Project/Scripts/GameDatas/TileData.cs
  Assets/Project/Scripts/GameDatas/TileData.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NumberTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NumberTileController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs
Labels: feature

#229 ワーニング修正
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
Labels: refactoring

#235 Touch scriptのデバッグプリントを消す
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/ThirdParties/TouchScript/Scripts/InputSources/StandardInput.cs
  Assets/ThirdParties/TouchScript/license.txt
Labels: improvement

#242 PanelのinitPosをGUIで表示する
  Assets/Project/Scripts/Editor/StageDataEditor.cs
Labels: bug
