Repository LITO-apps/Treevel-client, pull requests merged in 2019-11, with the labels that each got.

#193 ステージの概要をポップアップウィンドウで表示
  Assets/Project/Prefabs/StageSelectScene/OverviewPopup.prefab
  Assets/Project/Prefabs/StageSelectScene/OverviewPopup.prefab.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/ConfigScene.unity
  Assets/Project/Scenes/StageSelectScene.unity
  Assets/Project/Scripts/ConfigScene/HideOverviewController.cs
  Assets/Project/Scripts/ConfigScene/HideOverviewController.cs.meta
  Assets/Project/Scripts/StageSelectScene/OverviewPopup.cs
  Assets/Project/Scripts/StageSelectScene/OverviewPopup.cs.meta
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
Labels: enhancement

#199 fix inconsitency in animation clip name
  Assets/Project/Scripts/GamePlayScene/Panel/LifeNumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
Labels: bug

#192 WIP: ツイートにスクリーンショットを添付する
  .gitignore
  Assets/Plugins.meta
  Assets/Plugins/Android.meta
  Assets/Plugins/Android/AndroidManifest.xml
  Assets/Plugins/Android/AndroidManifest.xml.meta
  Assets/Plugins/Android/res.meta
  Assets/Plugins/Android/res/xml.meta
  Assets/Plugins/Android/res/xml/filepaths.xml
  Assets/Plugins/Android/res/xml/filepaths.xml.meta
  Assets/Plugins/Android/support-core-utils-25.3.1.aar
  Assets/Plugins/Android/support-core-utils-25.3.1.aar.meta
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/StreamingAssets.meta
  Assets/StreamingAssets/.gitkeep
  Assets/ThirdParties/SocialConnector.meta
  Assets/ThirdParties/SocialConnector/Editor.meta
  Assets/ThirdParties/SocialConnector/Editor/SocialConnectorPostProcess.cs
  Assets/ThirdParties/SocialConnector/Editor/SocialConnectorPostProcess.cs.meta
  Assets/ThirdParties/SocialConnector/LICENSE.txt
  Assets/ThirdParties/SocialConnector/LICENSE.txt.meta
  Assets/ThirdParties/SocialConnector/Plugins.meta
  Assets/ThirdParties/SocialConnector/Plugins/SocialConnector.mm
  Assets/ThirdParties/SocialConnector/Plugins/SocialConnector.mm.meta
  Assets/ThirdParties/SocialConnector/SocialConnector.cs
  Assets/ThirdParties/SocialConnector/SocialConnector.cs.meta
Labels: enhancement

#201 ゲーム一時停止ウィンドウをprefabにする
  Assets/Project/Prefabs/GamePlayScene/PauseWindow.prefab
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/PauseWindow.cs
  Assets/Project/Scripts/GamePlayScene/PauseWindow.cs.meta
Labels: refactoring

#219 ゲームクリア時の戻るボタンの処理を消してしまっていたのを戻す
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
Labels: improvement

#220 ゲーム結果ウィンドウに関する機能をスクリプトに分離する
  Assets/Project/Prefabs/GamePlayScene/ResultPopup.prefab
  Assets/Project/Prefabs/GamePlayScene/ResultPopup.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/ResultPopup.cs
  Assets/Project/Scripts/GamePlayScene/ResultPopup.cs.meta
Labels: improvement

#202 TurnCartridgeControllerのバグを直す
  Assets/Project/Resources/GameDatas/Stages/2_4.asset
  Assets/Project/Resources/GameDatas/Stages/2_4.asset.meta
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
Labels: improvement
