Repository LITO-apps/Treevel-client, pull requests merged in 2019-01, with the labels that each got.

#30 動かないパネルの実装
  Assets/Project/Prefabs/GamePlayScene/Panel/staticPanelPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/staticPanelPrefab.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Textures/GamePlayScene/Panel/staticPanel.png
  Assets/Project/Textures/GamePlayScene/Panel/staticPanel.png.meta
Labels: enhancement

#32 動くパネル（邪魔パネル）の実装
  Assets/Project/Prefabs/GamePlayScene/Panel/dynamicDummyPanelPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/dynamicDummyPanelPrefab.prefab.meta
  Assets/Project/Prefabs/GamePlayScene/Panel/staticDummyPanelPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/staticDummyPanelPrefab.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Textures/GamePlayScene/Panel/dynamicDummyPanel.png
  Assets/Project/Textures/GamePlayScene/Panel/dynamicDummyPanel.png.meta
  Assets/Project/Textures/GamePlayScene/Panel/staticDummyPanel.png
  Assets/Project/Textures/GamePlayScene/Panel/staticDummyPanel.png.meta
Labels: enhancement, waiting for review

#31 Componentのアタッチをコードで行うようにする
  Assets/Project/Prefabs/GamePlayScene/Bullet/normalBulletPrefab.prefab
  Assets/Project/Scripts/GamePlayScene/Bullet/CartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
Labels: enhancement, waiting for review

#33 パネル・タイル画像の大きさ設定にマジックナンバーを使わないようにする
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel5Prefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Panel/numberPanel5Prefab.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Textures/GamePlayScene/Panel/numberPanel5.png
  Assets/Project/Textures/GamePlayScene/Panel/numberPanel5.png.meta
Labels: refactoring, waiting for review

#35 銃弾画像の大きさ設定にマジックナンバーを用いない
  Assets/Project/Scripts/GamePlayScene/Bullet/CartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalCartridgeWarningController.cs
Labels: refactoring, waiting for review
