Repository LITO-apps/Treevel-client, pull requests merged in 2019-05, with the labels that each got.

#53 BulletDefinitionsではなく，メソッドで分割する
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
Labels: refactoring

#54 難易度によって選択できるステージを変える
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/LevelSelectScene/LevelSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/EasyStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/NormalStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs.meta
Labels: enhancement

#55 銃弾の先端をパネルが擦り抜ける
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
Labels: bug

#56 繰り返し出現しない銃弾の作成
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs.meta
  Assets/Project/Scripts/GamePlayScene/BulletWarning/HoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/HoleWarningController.cs.meta
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/Utils/Definitions/BulletDefinitions.cs
Labels: enhancement

#58 必ずパネルを撃ち抜く銃弾の実装
  Assets/Project/Prefabs/GamePlayScene/Bullet/Hole/aimingHolePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bullet/Hole/aimingHolePrefab.prefab.meta
  Assets/Project/Prefabs/GamePlayScene/BulletWarning/aimingHoleWarningPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/BulletWarning/aimingHoleWarningPrefab.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/AimingHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/AimingHoleWarningController.cs.meta
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalHoleWarningController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/Utils/Definitions/BulletDefinitions.cs
  Assets/Project/Textures/GamePlayScene/Bullet/Hole/aimingHole.png
  Assets/Project/Textures/GamePlayScene/Bullet/Hole/aimingHole.png.meta
  Assets/Project/Textures/GamePlayScene/BulletWarning/aimingHoleWarning.png
  Assets/Project/Textures/GamePlayScene/BulletWarning/aimingHoleWarning.png.meta
Labels: enhancement

#57 多様デバイスにおいて，ゲームプレイ画面で過去の画面を透過させないようにする
  Assets/Project/Prefabs/StageSelectScene/dummyBackgroundPrefab.prefab
  Assets/Project/Prefabs/StageSelectScene/dummyBackgroundPrefab.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/StageSelectScene.meta
  Assets/Project/Scenes/StageSelectScene/EasyStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/EasyStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/HardStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/HardStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/NormalStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/NormalStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/VeryHardStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/VeryHardStageSelectScene.unity.meta
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
Labels: bug

#59 文字列を定義して，参照するようにする
  Assets/Project/Scenes/StageSelectScene/EasyStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/HardStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/NormalStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/VeryHardStageSelectScene.unity
  Assets/Project/Scripts/ConfigScene/VolumeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/AimingHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/BulletWarningController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/StaticPanelController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/LevelSelectScene/LevelSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/AudioDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/PanelDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/PanelDefinitions.cs.meta
  Assets/Project/Scripts/Utils/Definitions/SizeDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs.meta
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs.meta
  Assets/Project/Scripts/Utils/Library.meta
  Assets/Project/Scripts/Utils/Library/PanelLabrary.cs
  Assets/Project/Scripts/Utils/Library/PanelLabrary.cs.meta
  Assets/Project/Scripts/Utils/Library/TileLabrary.cs
  Assets/Project/Scripts/Utils/Library/TileLabrary.cs.meta
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
Labels: enhancement

#60 記録画面 (仮) の実装
  Assets/Project/Prefabs/RecordScene.meta
  Assets/Project/Prefabs/RecordScene/graph.prefab
  Assets/Project/Prefabs/RecordScene/graph.prefab.meta
  Assets/Project/Prefabs/RecordScene/stageNum.prefab
  Assets/Project/Prefabs/RecordScene/stageNum.prefab.meta
  Assets/Project/Prefabs/RecordScene/successLine.prefab
  Assets/Project/Prefabs/RecordScene/successLine.prefab.meta
  Assets/Project/Scenes/ConfigScene.unity
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/RecordScene.unity
  Assets/Project/Scripts/ConfigScene/ResetController.cs
  Assets/Project/Scripts/ConfigScene/ResetController.cs.meta
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/RecordScene.meta
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs.meta
  Assets/Project/Scripts/StageSelectScene/EasyStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/NormalStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
  ProjectSettings/TagManager.asset
Labels: enhancement
