Repository LITO-apps/Treevel-client, pull requests merged in 2019-08, with the labels that each got.

#147 Feature/rename enum
  Assets/Project/Scripts/ConfigScene/ResetController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/EasyStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/NormalStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/BulletDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
Labels: refactoring

#148 コーディング規約の見直しと適用
  .astylerc
  .githooks/pre-commit
  Assets/Project/Scripts/ConfigScene/ResetController.cs
  Assets/Project/Scripts/ConfigScene/VolumeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/AimingHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/BulletWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Panel/StaticPanelController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NumberTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/LevelSelectScene/LevelSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/EasyStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/NormalStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/AudioDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/BulletDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/PanelDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/SizeDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs
  Assets/Project/Scripts/Utils/Library/PanelLabrary.cs
  Assets/Project/Scripts/Utils/Library/TileLabrary.cs
  Assets/Project/Scripts/Utils/Patterns/Singleton.cs
  Assets/Project/Scripts/Utils/Patterns/SingletonObject.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/MyPlayerPrefs.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
  README.md
Labels: improvement

#149 多言語対応機能
  Assets/Project/Resources/GameDatas.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Resources/GameDatas/translation.csv.meta
  Assets/Project/Scenes/ConfigScene.unity
  Assets/Project/Scripts/Editor.meta
  Assets/Project/Scripts/Editor/MultiLanguageTextEditor.cs
  Assets/Project/Scripts/Editor/MultiLanguageTextEditor.cs.meta
  Assets/Project/Scripts/UIComponents.meta
  Assets/Project/Scripts/UIComponents/LanguageChangeHandler.cs
  Assets/Project/Scripts/UIComponents/LanguageChangeHandler.cs.meta
  Assets/Project/Scripts/UIComponents/MultiLanguageText.cs
  Assets/Project/Scripts/UIComponents/MultiLanguageText.cs.meta
  Assets/Project/Scripts/Utils/CSVReader.cs
  Assets/Project/Scripts/Utils/CSVReader.cs.meta
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs.meta
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/TextUtils.meta
  Assets/Project/Scripts/Utils/TextUtils/LanguageUtility.cs
  Assets/Project/Scripts/Utils/TextUtils/LanguageUtility.cs.meta
Labels: enhancement

#146 難易度選択画面に SnapScrollView を使用する
  .githooks/pre-commit
  Assets/Project/Prefabs/StageSelectScene/levelContents.prefab
  Assets/Project/Prefabs/StageSelectScene/levelContents.prefab.meta
  Assets/Project/Scenes/LevelSelectScene.unity
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene.meta
  Assets/Project/Scenes/StageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/EasyStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/EasyStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/HardStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/HardStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/NormalStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/VeryHardStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/VeryHardStageSelectScene.unity.meta
  Assets/Project/Scripts/LevelSelectScene.meta
  Assets/Project/Scripts/LevelSelectScene/LevelSelectDirector.cs
  Assets/Project/Scripts/LevelSelectScene/LevelSelectDirector.cs.meta
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/EasyStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/EasyStageSelectDirector.cs.meta
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/HardStageSelectDirector.cs.meta
  Assets/Project/Scripts/StageSelectScene/NormalStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/NormalStageSelectDirector.cs.meta
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/VeryHardStageSelectDirector.cs.meta
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#152 ToggleGroup を使わない実装に変える
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs.meta
Labels: bug

#157 エディタ実行中以外は ToggleValueChanged を無視する
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs
Labels: bug

#144 銃弾の計算をライブラリ化する
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/BulletWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/Utils/Definitions/BulletDefinitions.cs
  Assets/Project/Scripts/Utils/Library/BulletLibrary.cs
  Assets/Project/Scripts/Utils/Library/BulletLibrary.cs.meta
  Assets/Project/Scripts/Utils/Library/Extension.meta
  Assets/Project/Scripts/Utils/Library/Extension/ExtensionVector2.cs
  Assets/Project/Scripts/Utils/Library/Extension/ExtensionVector2.cs.meta
  Assets/Project/Scripts/Utils/Library/PanelLabrary.cs.meta
  Assets/Project/Scripts/Utils/Library/PanelLibrary.cs
  Assets/Project/Scripts/Utils/Library/PanelLibrary.cs.meta
  Assets/Project/Scripts/Utils/Library/TileLabrary.cs.meta
  Assets/Project/Scripts/Utils/Library/TileLibrary.cs
  Assets/Project/Scripts/Utils/Library/TileLibrary.cs.meta
Labels: refactoring

#154 [SerializedField]と[NonSerialized]を適切に用いる
  Assets/Project/Prefabs/GamePlayScene/Bullet/Cartridge/TurnCartridgePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/BulletGenerator/AimingHoleGenerator.prefab
  Assets/Project/Prefabs/GamePlayScene/BulletGenerator/NormalCartridgeGenerator.prefab
  Assets/Project/Prefabs/GamePlayScene/BulletGenerator/NormalHoleGenerator.prefab
  Assets/Project/Prefabs/GamePlayScene/BulletGenerator/TurnCartridgeGenerator.prefab
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/RecordScene.unity
  Assets/Project/Scripts/Editor/NonEditableDrawer.cs
  Assets/Project/Scripts/Editor/NonEditableDrawer.cs.meta
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Attributes.meta
  Assets/Project/Scripts/Utils/Attributes/NonEditableAttribute.cs
  Assets/Project/Scripts/Utils/Attributes/NonEditableAttribute.cs.meta
  README.md
Labels: refactoring

#153 ドキュメンテーションコメントを記述する
  Assets/Project/Scripts/ConfigScene/ResetController.cs
  Assets/Project/Scripts/ConfigScene/VolumeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/AimingHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/BulletWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/CartridgeWarningController.cs
  Assets/Project/Scripts/GamePlayScene/BulletWarning/NormalHoleWarningController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NumberTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/AudioDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/BulletDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/PanelDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/SizeDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs
  Assets/Project/Scripts/Utils/Library/PanelLibrary.cs
  Assets/Project/Scripts/Utils/Library/TileLibrary.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/MyPlayerPrefs.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: improvement

#158 記録画面のリファクタリングと描画時の非同期処理の検討
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
Labels: improvement

#160 スクロール位置を表示する
  Assets/Project/Prefabs/RecordScene/levelContents.prefab
  Assets/Project/Prefabs/StageSelectScene/levelContents.prefab
  Assets/Project/Scenes/RecordScene.unity
  Assets/Project/Scenes/StageSelectScene.unity
Labels: enhancement

#162 曲がる銃弾が，曲がった直後のタイル上で再度曲がる場合に警告画像の表示が遅い問題の修正
  Assets/Project/Scripts/GamePlayScene/Bullet/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
Labels: improvement
