Repository LITO-apps/Treevel-client, pull requests merged in 2019-10, with the labels that each got.

#184 難易度をLevel，ステージをStageという名前に切り分ける
  Assets/Project/Scripts/ConfigScene/ResetController.cs
  Assets/Project/Scripts/RecordScene/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/LevelDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/LevelDefinitions.cs.meta
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
Labels: refactoring

#182 ゲーム中に一時停止を可能にする
  Assets/Project/Prefabs/GamePlayScene/Button.prefab
  Assets/Project/Prefabs/GamePlayScene/Button.prefab.meta
  Assets/Project/Prefabs/GamePlayScene/PauseWindow.prefab
  Assets/Project/Prefabs/GamePlayScene/PauseWindow.prefab.meta
  Assets/Project/Prefabs/GamePlayScene/ResultWindow.prefab
  Assets/Project/Prefabs/GamePlayScene/ResultWindow.prefab.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#190 画面の回転を禁止する
  ProjectSettings/ProjectSettings.asset
Labels: enhancement

#191 ゲームクリア時，アニメーション停止
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/LifeNumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
Labels: bug
