Repository LITO-apps/Treevel-client, pull requests merged in 2020-03, with the labels that each got.

#284 2.12f1 -> 3.2f1 にアップグレード
  Packages/manifest.json
  ProjectSettings/EditorSettings.asset
  ProjectSettings/ProjectVersion.txt
Labels: improvement

#288 アニメーションがアタッチされてないことによるエラーを解決
  Assets/Project/Prefabs/GamePlayScene/Panel/lifeNumberPanelPrefab.prefab
Labels: bug

#285 タイマーの実装
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/Utils/CustomTimer.cs
  Assets/Project/Scripts/Utils/CustomTimer.cs.meta
Labels: feature

#291 画面の切り替えをシーンの切り替えからキャンバスの切り替え処理に変更
  Assets/Project/Scenes/ConfigScene.unity
  Assets/Project/Scenes/ConfigScene.unity.meta
  Assets/Project/Scenes/LevelSelectScene.unity
  Assets/Project/Scenes/LevelSelectScene.unity.meta
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/RecordScene.unity
  Assets/Project/Scenes/RecordScene.unity.meta
  Assets/Project/Scenes/TutorialScene.unity
  Assets/Project/Scenes/TutorialScene.unity.meta
  Assets/Project/Scripts/MenuSelectScene/Config.meta
  Assets/Project/Scripts/MenuSelectScene/Config/HideOverviewController.cs
  Assets/Project/Scripts/MenuSelectScene/Config/HideOverviewController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Config/ResetController.cs
  Assets/Project/Scripts/MenuSelectScene/Config/ResetController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Config/VolumeController.cs
  Assets/Project/Scripts/MenuSelectScene/Config/VolumeController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectDirector.cs.meta
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs
  Assets/Project/Scripts/MenuSelectScene/MenuSelectToggle.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Record.meta
  Assets/Project/Scripts/MenuSelectScene/Record/RecordDirector.cs
  Assets/Project/Scripts/MenuSelectScene/Record/RecordDirector.cs.meta
  Assets/Project/Scripts/MenuSelectScene/TransitionSelfToggle.cs
  Assets/Project/Scripts/MenuSelectScene/TransitionSelfToggle.cs.meta
Labels: 1, improvement

#287 Addressable Asset System - Scene load / unload
  .gitignore
  Assets/AddressableAssetsData.meta
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
  Assets/AddressableAssetsData/AddressableAssetSettings.asset.meta
  Assets/AddressableAssetsData/AssetGroupTemplates.meta
  Assets/AddressableAssetsData/AssetGroupTemplates/Packed Assets.asset
  Assets/AddressableAssetsData/AssetGroupTemplates/Packed Assets.asset.meta
  Assets/AddressableAssetsData/AssetGroups.meta
  Assets/AddressableAssetsData/AssetGroups/Built In Data.asset
  Assets/AddressableAssetsData/AssetGroups/Built In Data.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Packed Assets.asset
  Assets/AddressableAssetsData/AssetGroups/Packed Assets.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/36fdf415407fc4d90bf691d9413d4847_BundledAssetGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/36fdf415407fc4d90bf691d9413d4847_BundledAssetGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/36fdf415407fc4d90bf691d9413d4847_ContentUpdateGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/36fdf415407fc4d90bf691d9413d4847_ContentUpdateGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/498c298ab693c4524a8659296e45f36a_PlayerDataGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/498c298ab693c4524a8659296e45f36a_PlayerDataGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/8f864bf0c7b5142f585c1a17b629e9d8_BundledAssetGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/8f864bf0c7b5142f585c1a17b629e9d8_BundledAssetGroupSchema.asset.meta
  Assets/AddressableAssetsData/AssetGroups/Schemas/8f864bf0c7b5142f585c1a17b629e9d8_ContentUpdateGroupSchema.asset
  Assets/AddressableAssetsData/AssetGroups/Schemas/8f864bf0c7b5142f585c1a17b629e9d8_ContentUpdateGroupSchema.asset.meta
  Assets/AddressableAssetsData/DataBuilders.meta
  Assets/AddressableAssetsData/DataBuilders/BuildScriptFastMode.asset
  Assets/AddressableAssetsData/DataBuilders/BuildScriptFastMode.asset.meta
  Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedMode.asset
  Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedMode.asset.meta
  Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedPlayMode.asset
  Assets/AddressableAssetsData/DataBuilders/BuildScriptPackedPlayMode.asset.meta
  Assets/AddressableAssetsData/DataBuilders/BuildScriptVirtualMode.asset
  Assets/AddressableAssetsData/DataBuilders/BuildScriptVirtualMode.asset.meta
  Assets/AddressableAssetsData/DefaultObject.asset
  Assets/AddressableAssetsData/DefaultObject.asset.meta
  Assets/Project/Scripts/GamePlayScene/PauseWindow.cs
  Assets/Project/Scripts/GamePlayScene/ResultPopup.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs.meta
  Packages/manifest.json
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#294 プログレスバーの実装
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Prefabs/ProgressBar.prefab
  Assets/Project/Prefabs/ProgressBar.prefab.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/UIManager.cs
  Assets/Project/Scripts/MenuSelectScene/UIManager.cs.meta
  Assets/Project/Scripts/UIComponents/ProgressBar.cs
  Assets/Project/Scripts/UIComponents/ProgressBar.cs.meta
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
Labels: feature, 全般

#307 レベル選択画面をスクロール可能にする
  Assets/Project/Scenes/MenuSelectScene.unity
Labels: feature

#327 overviewpopup背景微調整
  Assets/Project/Prefabs/StageSelectScene/OverviewPopup.prefab
Labels: 1, improvement

#305 ステージ選択画面仮画像組み込み
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Prefabs/StageSelectScene/BackButton.prefab
  Assets/Project/Prefabs/StageSelectScene/BackButton.prefab.meta
  Assets/Project/Prefabs/StageSelectScene/LeftButton.prefab
  Assets/Project/Prefabs/StageSelectScene/LeftButton.prefab.meta
  Assets/Project/Prefabs/StageSelectScene/RightButton.prefab
  Assets/Project/Prefabs/StageSelectScene/RightButton.prefab.meta
  Assets/Project/Prefabs/StageSelectScene/Stage.prefab
  Assets/Project/Prefabs/StageSelectScene/Stage.prefab.meta
  Assets/Project/Prefabs/StageSelectScene/Tree.prefab
  Assets/Project/Prefabs/StageSelectScene/Tree.prefab.meta
  Assets/Project/Prefabs/StageSelectScene/TreeName.prefab
  Assets/Project/Prefabs/StageSelectScene/TreeName.prefab.meta
  Assets/Project/Prefabs/StageSelectScene/levelContents.prefab
  Assets/Project/Scenes/StageSelectScene.meta
  Assets/Project/Scenes/StageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutomnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutomnStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity.meta
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity.meta
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/ResultPopup.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs
  Assets/Project/Scripts/Utils/Library/TreeLibrary.cs
  Assets/Project/Scripts/Utils/Library/TreeLibrary.cs.meta
  Assets/Project/Textures/StageSelectScene/back.png
  Assets/Project/Textures/StageSelectScene/back.png.meta
  Assets/Project/Textures/StageSelectScene/back_highligted.png
  Assets/Project/Textures/StageSelectScene/back_highligted.png.meta
  Assets/Project/Textures/StageSelectScene/back_pressed.png
  Assets/Project/Textures/StageSelectScene/back_pressed.png.meta
  Assets/Project/Textures/StageSelectScene/left.png
  Assets/Project/Textures/StageSelectScene/left.png.meta
  Assets/Project/Textures/StageSelectScene/left_highlighted.png
  Assets/Project/Textures/StageSelectScene/left_highlighted.png.meta
  Assets/Project/Textures/StageSelectScene/left_pressed.png
  Assets/Project/Textures/StageSelectScene/left_pressed.png.meta
  Assets/Project/Textures/StageSelectScene/right.png
  Assets/Project/Textures/StageSelectScene/right.png.meta
  Assets/Project/Textures/StageSelectScene/right_highlited.png
  Assets/Project/Textures/StageSelectScene/right_highlited.png.meta
  Assets/Project/Textures/StageSelectScene/right_pressed.png
  Assets/Project/Textures/StageSelectScene/right_pressed.png.meta
  Assets/Project/Textures/StageSelectScene/stage.png
  Assets/Project/Textures/StageSelectScene/stage.png.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: design
