Repository LITO-apps/Treevel-client, pull requests merged in 2020-10, with the labels that each got.

#554 ポーズ中は BGM の音量を小さくする
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/Utils/SoundManager.cs
Labels: _1

#556 【StageSelectScene】ステージ概要ポップアップUI作成
  Assets/Project/Actors/UIs/StageSelectScene/Gimmick Overview.prefab
  Assets/Project/Actors/UIs/StageSelectScene/OverviewPopup.prefab
  Assets/Project/Actors/UIs/StageSelectScene/PreviewWindow.png
  Assets/Project/Actors/UIs/StageSelectScene/PreviewWindow.png.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scripts/StageSelectScene/OverviewPopup.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
Labels: _4

#557 環境を管理し，エディタから変更可能にする
  Assets/Project/Scripts/Editor/ChangeEnvironment.cs
  Assets/Project/Scripts/Editor/ChangeEnvironment.cs.meta
  Assets/Project/Scripts/StartUpScene/StartUpDirector.cs
  ProjectSettings/ProjectSettings.asset
Labels: _2, __1

#573 Staticボトル、Dummyボトル見えない不具合修正
  Assets/Project/Actors/Bottles/Dynamic/AttackableDummy/AttackableDummyBottlePrefab.prefab
  Assets/Project/Actors/Bottles/Dynamic/DynamicDummy/DynamicDummyBottlePrefab.prefab
  Assets/Project/Actors/Bottles/Dynamic/Life/LifeBottlePrefab.prefab
  Assets/Project/Actors/Bottles/Normal/NormalBottlePrefab.prefab
  Assets/Project/Actors/Bottles/StaticDummy/StaticDummyBottlePrefab.prefab
  Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/TornadoController.cs
  Assets/Project/Scripts/GamePlayScene/ObjectUnifier.cs
Labels: _1

#574 `Unity 2020.1.7f1` にアップグレードする
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  ProjectSettings/VersionControlSettings.asset
  UserSettings/EditorUserSettings.asset
Labels: _1

#576 データタイプを編集する際データをリセットする
  Assets/Project/Scripts/Editor/EditorExtension.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
Labels: _3

#584 fix UnityEventDrawer
  Assets/Project/Scripts/Editor/UnityEventDrawer.cs
Labels: _2

#585 Vector2Extension.Normalize 周りのリファクタリング
  Assets/Project/Scripts/Common/Extensions/Vector2Extension.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Bottle/DynamicBottleController.cs
Labels: _1

#582 個別記録画面を実装するための準備をする
  Assets/Project/Materials/RoundedCornersMaterial.mat
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/GamePlaySceneSettings.lighting
  Assets/Project/Scenes/GamePlaySceneSettings.lighting.meta
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/MenuSelectSceneSettings.lighting
  Assets/Project/Scenes/MenuSelectSceneSettings.lighting.meta
  Assets/Project/Scenes/StageSelectScene/AutumnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutumnStageSelectSceneSettings.lighting
  Assets/Project/Scenes/StageSelectScene/AutumnStageSelectSceneSettings.lighting.meta
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectSceneSettings.lighting
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectSceneSettings.lighting.meta
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectSceneSettings.lighting
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectSceneSettings.lighting.meta
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectSceneSettings.lighting
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectSceneSettings.lighting.meta
  Assets/Project/Scenes/StartUpScene.unity
  Assets/Project/Scenes/StartUpSceneSettings.lighting
  Assets/Project/Scenes/StartUpSceneSettings.lighting.meta
  Assets/Project/Scripts/Common/Entities/TextIndex.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/RecordDirector.cs
Labels: _2

#593 fix warning: "ErrorLoadDataFailed is not a valid enum value"
  Assets/Project/Scripts/Common/Entities/TextIndex.cs
Labels: _1

#586 ゲーム画面でカメラ範囲を縮小させない
  Assets/Project/Actors/Bottles/Dynamic/AttackableDummy/AttackableDummyBottlePrefab.prefab
  Assets/Project/Actors/Bottles/Dynamic/DynamicDummy/DynamicDummyBottlePrefab.prefab
  Assets/Project/Actors/Bottles/Effect/Dark/DarkEffectPrefab.prefab
  Assets/Project/Actors/Bottles/Effect/Life/LifeEffectPrefab.prefab
  Assets/Project/Actors/Bottles/Effect/Selfish/SelfishEffectPrefab.prefab
  Assets/Project/Actors/Bottles/Normal/NormalBottlePrefab.prefab
  Assets/Project/Actors/Bottles/StaticDummy/StaticDummyBottlePrefab.prefab
  Assets/Project/Actors/Gimmicks/AimingMeteorite/AimingMeteoritePrefab.prefab
  Assets/Project/Actors/Gimmicks/AimingMeteorite/AimingMeteoriteWarningPrefab.prefab
  Assets/Project/Actors/Gimmicks/GustWind/GustWindPrefab.prefab
  Assets/Project/Actors/Gimmicks/Meteorite/MeteoritePrefab.prefab
  Assets/Project/Actors/Gimmicks/Meteorite/MeteoriteWarningPrefab.prefab
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeamPrefab.prefab
  Assets/Project/Actors/Gimmicks/Thunder/ThunderPrefab.prefab
  Assets/Project/Actors/Gimmicks/Tornado/TornadoPrefab.prefab
  Assets/Project/Actors/Gimmicks/Tornado/TornadoWarningPrefab.prefab
  Assets/Project/Actors/Tiles/Holy/HolyTilePrefab.prefab
  Assets/Project/Actors/Tiles/Ice/IceTilePrefab.prefab
  Assets/Project/Actors/Tiles/Normal/NormalTilePrefab.prefab
  Assets/Project/Actors/Tiles/Spiderweb/SpiderwebTilePrefab.prefab
  Assets/Project/Actors/Tiles/Warp/WarpTilePrefab.prefab
  Assets/Project/Actors/UIs/Common/ProgressBar.prefab
  Assets/Project/Actors/UIs/GamePlayScene/Background.prefab
  Assets/Project/Actors/UIs/GamePlayScene/Background.prefab.meta
  Assets/Project/GameDatas/Stages/Spring_1/1.asset
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/Common/Components/SpriteRendererUnifier.cs
  Assets/Project/Scripts/Common/Components/SpriteRendererUnifier.cs.meta
  Assets/Project/Scripts/Common/Utils/Constants.cs
  Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/DisplayUnifier.cs
  Assets/Project/Scripts/Modules/GamePlayScene/GameSpriteRendererUnifier.cs
  Assets/Project/Scripts/Modules/GamePlayScene/GameSpriteRendererUnifier.cs.meta
  Assets/Project/Scripts/Modules/GamePlayScene/GameWindowController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/GameWindowController.cs.meta
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/SolarBeamController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/ThunderController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/TornadoController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Tile/AbstractTileController.cs
Labels: _6, __1

#594 `EGimmickDirection` と `EBottleDirection` を統合する
  Assets/Project/Scripts/Common/Entities/BottleDirection.cs
  Assets/Project/Scripts/Common/Entities/BottleDirection.cs.meta
  Assets/Project/Scripts/Common/Entities/Direction.cs
  Assets/Project/Scripts/Common/Entities/Direction.cs.meta
  Assets/Project/Scripts/Common/Entities/GameDatas/GimmickData.cs
  Assets/Project/Scripts/Common/Utils/GimmickLibrary.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Bottle/SelfishEffectController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GustWindController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/SolarBeamController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/TornadoController.cs
Labels: _2

#597 StageButtonが押しにくい問題を解決
  Assets/Project/Actors/UIs/StageSelectScene/Stage.prefab
Labels: _1
