Repository LITO-apps/Treevel-client, pull requests merged in 2020-11, with the labels that each got.

#596 道の解放アニメーション途中に画面遷移した場合でも道の色を更新する
  Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/LineController.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/Modules/StageSelectScene/BranchController.cs
  Assets/Project/Scripts/Modules/StageSelectScene/StageSelectDirector.cs
Labels: _1

#595 霧ギミックの実装
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Actors/Gimmicks/Fog.meta
  Assets/Project/Actors/Gimmicks/Fog/FogPrefab.prefab
  Assets/Project/Actors/Gimmicks/Fog/FogPrefab.prefab.meta
  Assets/Project/Actors/Gimmicks/Fog/fog.mat
  Assets/Project/Actors/Gimmicks/Fog/fog.mat.meta
  Assets/Project/Actors/Gimmicks/Fog/fog01.png
  Assets/Project/Actors/Gimmicks/Fog/fog01.png.meta
  Assets/Project/Actors/Gimmicks/Fog/fog02.png
  Assets/Project/Actors/Gimmicks/Fog/fog02.png.meta
  Assets/Project/Actors/Gimmicks/Fog/fog03.png
  Assets/Project/Actors/Gimmicks/Fog/fog03.png.meta
  Assets/Project/GameDatas/Stages/Spring_2/1.asset
  Assets/Project/Scripts/Common/Entities/FailureReasonType.cs
  Assets/Project/Scripts/Common/Entities/GameDatas/GimmickData.cs
  Assets/Project/Scripts/Common/Entities/GimmickType.cs
  Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
  Assets/Project/Scripts/Common/Utils/Constants.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/FogController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/FogController.cs.meta
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
Labels: _5

#609 【ステージ概要】機能実装
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scripts/Common/Entities/GameDatas/StageData.cs
  Assets/Project/Scripts/Common/Entities/TreeId.cs
  Assets/Project/Scripts/Common/Networks/IServerRequest.cs
  Assets/Project/Scripts/Common/Networks/Objects.meta
  Assets/Project/Scripts/Common/Networks/Objects/StageStats.cs
  Assets/Project/Scripts/Common/Networks/Objects/StageStats.cs.meta
  Assets/Project/Scripts/Common/Networks/Requests/GetStageStatsRequest.cs
  Assets/Project/Scripts/Common/Networks/Requests/GetStageStatsRequest.cs.meta
  Assets/Project/Scripts/Modules/StageSelectScene/OverviewPopup.cs
  Assets/Project/Scripts/Modules/StageSelectScene/StageSelectDirector.cs
Labels: _3

#613 EBottleTypeを拡張し、攻撃可能かどうかを返す
  Assets/Project/Scripts/Common/Entities/BottleType.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Bottle/AbstractBottleController.cs
Labels: _1

#615 `ERow` と `EColumn` を0から数えるようにする
  Assets/Project/GameDatas/Stages/Spring_1/1.asset
  Assets/Project/GameDatas/Stages/Spring_1/10.asset
  Assets/Project/GameDatas/Stages/Spring_1/2.asset
  Assets/Project/GameDatas/Stages/Spring_1/3.asset
  Assets/Project/GameDatas/Stages/Spring_1/4.asset
  Assets/Project/GameDatas/Stages/Spring_1/5.asset
  Assets/Project/GameDatas/Stages/Spring_1/7.asset
  Assets/Project/GameDatas/Stages/Spring_1/8.asset
  Assets/Project/GameDatas/Stages/Spring_1/9.asset
  Assets/Project/GameDatas/Stages/Spring_2/1.asset
  Assets/Project/GameDatas/Stages/Spring_2/3.asset
  Assets/Project/GameDatas/Stages/Spring_2/4.asset
  Assets/Project/GameDatas/Stages/Spring_2/5.asset
  Assets/Project/GameDatas/Stages/Spring_3/1.asset
  Assets/Project/GameDatas/Stages/Summer_1/2.asset
  Assets/Project/GameDatas/Stages/Summer_1/3.asset
  Assets/Project/Scripts/Common/Entities/GimmickLine.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Modules/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/FogController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GustWindController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/MeteoriteController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/TornadoController.cs
Labels: _4, __1

#608 粉ギミックの実装
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Actors/Gimmicks/Powder.meta
  Assets/Project/Actors/Gimmicks/Powder/Powder AC.controller
  Assets/Project/Actors/Gimmicks/Powder/Powder AC.controller.meta
  Assets/Project/Actors/Gimmicks/Powder/Powder Icon.png
  Assets/Project/Actors/Gimmicks/Powder/Powder Icon.png.meta
  Assets/Project/Actors/Gimmicks/Powder/Powder@idle.anim
  Assets/Project/Actors/Gimmicks/Powder/Powder@idle.anim.meta
  Assets/Project/Actors/Gimmicks/Powder/PowderPrefab.prefab
  Assets/Project/Actors/Gimmicks/Powder/PowderPrefab.prefab.meta
  Assets/Project/Actors/Gimmicks/Powder/Sand01.png
  Assets/Project/Actors/Gimmicks/Powder/Sand01.png.meta
  Assets/Project/Actors/Gimmicks/Powder/Sand02.png
  Assets/Project/Actors/Gimmicks/Powder/Sand02.png.meta
  Assets/Project/Actors/Gimmicks/Powder/Sand03.png
  Assets/Project/Actors/Gimmicks/Powder/Sand03.png.meta
  Assets/Project/Actors/Gimmicks/Powder/Sand04.png
  Assets/Project/Actors/Gimmicks/Powder/Sand04.png.meta
  Assets/Project/Actors/Gimmicks/Powder/Sand05.png
  Assets/Project/Actors/Gimmicks/Powder/Sand05.png.meta
  Assets/Project/Actors/Gimmicks/Powder/Sand06.png
  Assets/Project/Actors/Gimmicks/Powder/Sand06.png.meta
  Assets/Project/Actors/Gimmicks/Powder/SandBackground.png
  Assets/Project/Actors/Gimmicks/Powder/SandBackground.png.meta
  Assets/Project/Actors/Gimmicks/Powder/SandMaterial.mat
  Assets/Project/Actors/Gimmicks/Powder/SandMaterial.mat.meta
  Assets/Project/Actors/Gimmicks/Powder/SandParticle.png
  Assets/Project/Actors/Gimmicks/Powder/SandParticle.png.meta
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowder AC.controller
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowder AC.controller.meta
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowder@action.anim
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowder@action.anim.meta
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowder@idle.anim
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowder@idle.anim.meta
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowderPrefab.prefab
  Assets/Project/Actors/Gimmicks/Powder/SandPiledUpPowderPrefab.prefab.meta
  Assets/Project/GameDatas/Stages/Spring_2/2.asset
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/Common/Entities/FailureReasonType.cs
  Assets/Project/Scripts/Common/Entities/GimmickType.cs
  Assets/Project/Scripts/Common/Entities/SeasonId.cs
  Assets/Project/Scripts/Common/Entities/SeasonId.cs.meta
  Assets/Project/Scripts/Common/Entities/TreeId.cs
  Assets/Project/Scripts/Common/Managers/AddressableAssetManager.cs
  Assets/Project/Scripts/Common/Utils/Constants.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Bottle/LifeEffectController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/GimmickGenerator.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Powder.meta
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Powder/PiledUpPowderController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Powder/PiledUpPowderController.cs.meta
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Powder/PowderController.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/Powder/PowderController.cs.meta
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
Labels: _1, _10

#614 個別記録画面のレイアウトに機能やデータ注入を実装する
  Assets/Project/Actors/UIs/MenuSelectScene/Record/ClearStageNum.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/BarGraph.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/BarGraphAxisLabel.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/BarGraphRoundedCorners.mat
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/BarGraphRoundedCorners.mat.meta
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused.meta
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused/Graph.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused/Graph.prefab.meta
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused/LevelContents.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused/LevelContents.prefab.meta
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused/SuccessLine.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/Unused/SuccessLine.prefab.meta
  Assets/Project/Materials/RoundedCornersMaterial.mat
  Assets/Project/Materials/RoundedCornersMaterial.mat.meta
  Assets/Project/Materials/SeasonSelectToggle.mat
  Assets/Project/Materials/SeasonSelectToggle.mat.meta
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/Common/Entities/GameDatas/StageData.cs
  Assets/Project/Scripts/Common/Managers/GameDataManager.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/ClearStageNumController.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/ClearStageNumController.cs.meta
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/GeneralRecordDirector.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs.meta
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/RecordDirector.cs
Labels: _6
