Repository LITO-apps/Treevel-client, pull requests merged in 2020-04, with the labels that each got.

#328 任意のデバイスでポーズ画面が画面全体を覆うように修正する
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
Labels: bug, ゲーム画面

#329 任意のシーンのCanvasScalerを統一する
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/Editor/CanvasScalerReplacer.cs
  Assets/Project/Scripts/Editor/CanvasScalerReplacer.cs.meta
Labels: design, 全般

#332 振動を消す
  Assets/Project/Scenes/MenuSelectScene.unity
Labels: invalid

#335 fix filename
  Assets/Project/Scripts/Utils/Definitions/AnimationDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/AnimationDefinitions.cs.meta
Labels: 1, refactoring, 全般

#348 タイルを予めシーンに配置する
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
Labels: improvement, ゲーム画面

#338 レベル選択画面のスクロールビューの拡大縮小
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/ScaleContent.cs
  Assets/Project/Scripts/MenuSelectScene/ScaleContent.cs.meta
Labels: レベル選択画面

#337 設定画面のデザイン適用
  Assets/Project/Prefabs/StageSelectScene/OverviewPopup.prefab
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/MenuSelectScene/Config/HideOverviewController.cs
  Assets/Project/Scripts/MenuSelectScene/Config/VolumeController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings.meta
  Assets/Project/Scripts/MenuSelectScene/Settings/BGMController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/BGMController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Settings/ResetController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/ResetController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Settings/SEController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/SEController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Settings/StageDetailsController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/StageDetailsController.cs.meta
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/SwitchStageDetailsController.cs
  Assets/Project/Scripts/StageSelectScene/SwitchStageDetailsController.cs.meta
  Assets/Project/Scripts/Utils/Definitions/AudioDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Textures/MenuSelectScene/circle.png
  Assets/Project/Textures/MenuSelectScene/circle.png.meta
Labels: feature

#352 Refactoring/bullet generator
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/TurnCartridgeGenerator.cs
Labels: refactoring

#358 Delete unused objects (were made when #337 merge conflict was solved)
  Assets/Project/Scenes/MenuSelectScene.unity
Labels: refactoring

#364 SocialConnectorの利用をやめ，テキストとハッシュタグのみをTwitterで投稿可能にする
  Assets/Plugins/Android.meta
  Assets/Plugins/Android/AndroidManifest.xml
  Assets/Plugins/Android/AndroidManifest.xml.meta
  Assets/Plugins/Android/res.meta
  Assets/Plugins/Android/res/xml.meta
  Assets/Plugins/Android/res/xml/filepaths.xml
  Assets/Plugins/Android/res/xml/filepaths.xml.meta
  Assets/Plugins/Android/support-core-utils-25.3.1.aar
  Assets/Plugins/Android/support-core-utils-25.3.1.aar.meta
  Assets/Project/Scripts/GamePlayScene/FailurePopupController.cs
  Assets/Project/Scripts/GamePlayScene/SuccessPopupController.cs
  Assets/StreamingAssets.meta
  Assets/StreamingAssets/.gitkeep
  Assets/ThirdParties/SocialConnector.meta
  Assets/ThirdParties/SocialConnector/Editor.meta
  Assets/ThirdParties/SocialConnector/Editor/SocialConnectorPostProcess.cs
  Assets/ThirdParties/SocialConnector/Editor/SocialConnectorPostProcess.cs.meta
  Assets/ThirdParties/SocialConnector/LICENSE.txt
  Assets/ThirdParties/SocialConnector/LICENSE.txt.meta
  Assets/ThirdParties/SocialConnector/Plugins.meta
  Assets/ThirdParties/SocialConnector/Plugins/SocialConnector.mm
  Assets/ThirdParties/SocialConnector/Plugins/SocialConnector.mm.meta
  Assets/ThirdParties/SocialConnector/SocialConnector.cs
  Assets/ThirdParties/SocialConnector/SocialConnector.cs.meta
Labels: invalid

#366 設定画面からレビューできるようにする
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/Settings/ReviewController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/ReviewController.cs.meta
Labels: feature

#361 パネルとタイルの依存性をなくす
  Assets/Project/AddressableResources/GameDatas/Stages/1_1.asset
  Assets/Project/Prefabs/GamePlayScene/Tile/NormalTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/WarpTilePrefab.prefab
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs.meta
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/AbstractPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/AbstractPanelController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/IEnterTileHandler.cs
  Assets/Project/Scripts/GamePlayScene/Panel/IEnterTileHandler.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/IPanelSuccessHandler.cs
  Assets/Project/Scripts/GamePlayScene/Panel/IPanelSuccessHandler.cs.meta
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/PanelGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Panel/StaticPanelController.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/AbstractTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/AbstractTileController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs
  Assets/Project/Scripts/Utils/Library/Extension/ExtensionVector2.cs
  Assets/Project/Scripts/Utils/Library/TileLibrary.cs
Labels: refactoring, ゲーム画面

#367 Refactoring of GamePlayDirector
  Assets/Project/Prefabs/GamePlayScene/PauseWindow.prefab
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/GamePlayScene/Bullet/Controllers/NormalHoleController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Controllers/TurnCartridgeController.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/AimingHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/BulletGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/BulletGroupGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/NormalCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/NormalHoleGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Bullet/Generators/TurnCartridgeGenerator.cs
  Assets/Project/Scripts/GamePlayScene/DisplayUnifier.cs
  Assets/Project/Scripts/GamePlayScene/DisplayUnifier.cs.meta
  Assets/Project/Scripts/GamePlayScene/FailurePopupController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Panel/DynamicPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/LifeNumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/Panel/NumberPanelController.cs
  Assets/Project/Scripts/GamePlayScene/PauseWindow.cs
  Assets/Project/Scripts/GamePlayScene/StageGenerator.cs
  Assets/Project/Scripts/Utils/Patterns/StateMachine.meta
  Assets/Project/Scripts/Utils/Patterns/StateMachine/State.cs
  Assets/Project/Scripts/Utils/Patterns/StateMachine/State.cs.meta
  Assets/Project/Scripts/Utils/Patterns/StateMachine/StateMachine.cs
  Assets/Project/Scripts/Utils/Patterns/StateMachine/StateMachine.cs.meta
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: refactoring, ゲーム画面
