Repository LITO-apps/Treevel-client, pull requests merged in 2020-05, with the labels that each got.

#373 ステータスバーを表示する
  Assets/Project/Scripts/MenuSelectScene/UIManager.cs
  Assets/Project/Scripts/UIComponents/StatusBarController.cs
  Assets/Project/Scripts/UIComponents/StatusBarController.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: _4

#379 スプラッシュ画面作成
  Assets/Project/Prefabs/LevelSelectScene/LevelTree.prefab
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StartUpScene.unity
  Assets/Project/Scenes/StartUpScene.unity.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs
  Assets/Project/Scripts/MenuSelectScene/UIManager.cs
  Assets/Project/Scripts/StartUpScene.meta
  Assets/Project/Scripts/StartUpScene/StartUpDirector.cs
  Assets/Project/Scripts/StartUpScene/StartUpDirector.cs.meta
  Assets/Project/Scripts/UIComponents/FadeObject2D.cs
  Assets/Project/Scripts/UIComponents/FadeObject2D.cs.meta
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  Assets/Project/Scripts/Utils/GameDataBase.cs
  Assets/Project/Textures/logo.png
  Assets/Project/Textures/logo.png.meta
  Assets/Project/Textures/title.png
  Assets/Project/Textures/title.png.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
Labels: _3

#387 チュートリアルUI作成
  Assets/Project/Prefabs/GamePlayScene/TutorialWindow.prefab
  Assets/Project/Prefabs/GamePlayScene/TutorialWindow.prefab.meta
  Assets/Project/Scenes/GamePlayScene.unity
Labels: _1

#381 ネットワーク基盤実装
  Assets/Project/Scripts/Networks.meta
  Assets/Project/Scripts/Networks/IServerRequest.cs
  Assets/Project/Scripts/Networks/IServerRequest.cs.meta
  Assets/Project/Scripts/Networks/NetworkService.cs
  Assets/Project/Scripts/Networks/NetworkService.cs.meta
  Assets/Project/Scripts/Networks/Requests.meta
  Assets/Project/Scripts/Networks/Requests/HelloWorldRequest.cs
  Assets/Project/Scripts/Networks/Requests/HelloWorldRequest.cs.meta
  Assets/Project/Scripts/StartUpScene/StartUpDirector.cs
  Assets/Project/Scripts/Utils/Library/UnityWebRequestAwaiter.cs
  Assets/Project/Scripts/Utils/Library/UnityWebRequestAwaiter.cs.meta
  Assets/csc.rsp
Labels: _5

#380 多様なデバイスにUIを対応させる
  Assets/Project/Prefabs/GamePlayScene/PauseWindow.prefab
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutomnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity
  Assets/Project/Scenes/StartUpScene.unity
  Assets/Project/Scripts/Editor/CanvasScalerReplacer.cs
  Assets/Project/Scripts/Editor/TextChecker.cs
  Assets/Project/Scripts/GamePlayScene/DisplayUnifier.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/MenuSelectScene/ScaleContent.cs
  Assets/Project/Scripts/UIComponents/SafeAreaPanel.cs
  Assets/Project/Scripts/UIComponents/SafeAreaPanel.cs.meta
  Assets/Project/Scripts/UIComponents/StatusBarController.cs
Labels: _5

#388 namespaceの記述忘れの修正
  Assets/Project/Scripts/GamePlayScene/DisplayUnifier.cs
  Assets/Project/Scripts/Networks/NetworkService.cs
Labels: _1, refactoring

#390 ゴミ掃除
  Assets/Project/Scenes/GamePlayScene.unity
Labels: invalid

#389 チュートリアル機能実装
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_1.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_10.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_2.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_3.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_4.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_5.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_6.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_7.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_8.asset
  Assets/Project/AddressableResources/GameDatas/Stages/1_9.asset
  Assets/Project/AddressableResources/GameDatas/Stages/2_1.asset
  Assets/Project/AddressableResources/GameDatas/Stages/2_2.asset
  Assets/Project/AddressableResources/GameDatas/Stages/2_3.asset
  Assets/Project/AddressableResources/GameDatas/Stages/2_4.asset
  Assets/Project/AddressableResources/GameDatas/Stages/2_5.asset
  Assets/Project/AddressableResources/GameDatas/Tutorials.meta
  Assets/Project/AddressableResources/GameDatas/Tutorials/1_1.png
  Assets/Project/AddressableResources/GameDatas/Tutorials/1_1.png.meta
  Assets/Project/AddressableResources/GameDatas/Tutorials/1_2.mp4
  Assets/Project/AddressableResources/GameDatas/Tutorials/1_2.mp4.meta
  Assets/Project/Prefabs/GamePlayScene/TutorialWindow.prefab
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Editor/UnityEventDrawer.cs
  Assets/Project/Scripts/Editor/UnityEventDrawer.cs.meta
  Assets/Project/Scripts/GameDatas/StageData.cs
  Assets/Project/Scripts/GameDatas/TutorialData.cs
  Assets/Project/Scripts/GameDatas/TutorialData.cs.meta
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/Utils/Attributes/EnumActionAttribute.cs
  Assets/Project/Scripts/Utils/Attributes/EnumActionAttribute.cs.meta
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: _5

#396 fix:StaticDummyBottle、DynamicDummyBottleが表示されなくなっている
  Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
Labels: 1

#397 Unityバージョンアップでの差分を洗い出してコミット
  ProjectSettings/AudioManager.asset
  ProjectSettings/DeviceSimulatorSettings.asset
  ProjectSettings/DynamicsManager.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/PresetManager.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/VFXManager.asset
Labels: _1

#400 fix Waring: ErrorLoadSceneFailed is not a valid enum value
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
Labels: _1

#399 fix specification of CustomTimer
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/Utils/CustomTimer.cs
Labels: _1

#401 レベル選択画面の道の実装
  Assets/Project/Prefabs/LevelSelectScene/Road.prefab
  Assets/Project/Prefabs/LevelSelectScene/Road.prefab.meta
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/Editor/RoadDrawer.cs
  Assets/Project/Scripts/Editor/RoadDrawer.cs.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/ScaleContent.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Textures/LevelSelectScene/Materials.meta
  Assets/Project/Textures/LevelSelectScene/Materials/road.mat
  Assets/Project/Textures/LevelSelectScene/Materials/road.mat.meta
  Assets/Project/Textures/LevelSelectScene/road.jpg
  Assets/Project/Textures/LevelSelectScene/road.jpg.meta
  ProjectSettings/TagManager.asset
Labels: _7

#407 記録画面のSnapScroolViewのページサイズの修正
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/Record/RecordDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/SizeDefinitions.cs
Labels: _1

#408 ワープタイルが二回作られる問題を修正
  Assets/Project/AddressableResources/GameDatas/Stages/1_1.asset
  Assets/Project/Scripts/Editor/StageDataEditor.cs
Labels: _1

#409 レベル選択画面でのスクロール位置の保持
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/MenuSelectScene/SavableScrollRect.cs
  Assets/Project/Scripts/MenuSelectScene/SavableScrollRect.cs.meta
  Assets/Project/Scripts/MenuSelectScene/ScaleContent.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/BGMController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/LanguageChangeHandler.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/ResetController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/SEController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/SettingsManager.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/SettingsManager.cs.meta
  Assets/Project/Scripts/MenuSelectScene/Settings/StageDetailsController.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/SwitchStageDetailsController.cs
  Assets/Project/Scripts/Utils/Definitions/DefaultDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/UserSettings.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/UserSettings.cs.meta
  Assets/Project/Scripts/Utils/TextUtils/LanguageUtility.cs
Labels: _5
