Repository LITO-apps/Treevel-client, pull requests merged in 2020-08, with the labels that each got.

#498 ステージのクリア状況に応じたステージ選択画面の更新
  Assets/Project/Prefabs/LevelSelectScene/LevelTree.prefab
  Assets/Project/Prefabs/LevelSelectScene/Road.prefab
  Assets/Project/Prefabs/StageSelectScene/Branch.prefab
  Assets/Project/Prefabs/StageSelectScene/Stage.prefab
  Assets/Project/Prefabs/StageSelectScene/Tree.prefab
  Assets/Project/Scenes/StageSelectScene/AutomnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelTreeController.cs.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LineController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/TreeController.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/ResetController.cs
  Assets/Project/Scripts/StageSelectScene/BranchController.cs
  Assets/Project/Scripts/StageSelectScene/StageController.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/StageSelectScene/StageTreeController.cs
  Assets/Project/Scripts/StageSelectScene/StageTreeController.cs.meta
  Assets/Project/Scripts/Utils/Definitions/StageDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/MyPlayerPrefs.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: _5

#502 missing commit
  Assets/Project/Prefabs/ErrorMessageBox.prefab
Labels: improvement

#514 TileGenerator refactoring
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
Labels: _1

#513 【GamePlayScene】雷ギミック
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Actors.meta
  Assets/Project/Actors/Gimmicks.meta
  Assets/Project/Actors/Gimmicks/Thunder.meta
  Assets/Project/Actors/Gimmicks/Thunder/Cloud.png
  Assets/Project/Actors/Gimmicks/Thunder/Cloud.png.meta
  Assets/Project/Actors/Gimmicks/Thunder/ThundderAttackSE.mp3
  Assets/Project/Actors/Gimmicks/Thunder/ThundderAttackSE.mp3.meta
  Assets/Project/Actors/Gimmicks/Thunder/Thunder.png
  Assets/Project/Actors/Gimmicks/Thunder/Thunder.png.meta
  Assets/Project/Actors/Gimmicks/Thunder/ThunderAC.controller
  Assets/Project/Actors/Gimmicks/Thunder/ThunderAC.controller.meta
  Assets/Project/Actors/Gimmicks/Thunder/ThunderAttack.anim
  Assets/Project/Actors/Gimmicks/Thunder/ThunderAttack.anim.meta
  Assets/Project/Actors/Gimmicks/Thunder/ThunderPrefab.prefab
  Assets/Project/Actors/Gimmicks/Thunder/ThunderPrefab.prefab.meta
  Assets/Project/Actors/Gimmicks/Thunder/ThunderWarning.anim
  Assets/Project/Actors/Gimmicks/Thunder/ThunderWarning.anim.meta
  Assets/Project/AddressableResources/GameDatas/Stages/Spring_1/1.asset
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/GameDatas/GimmickData.cs
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/AbstractGimmickController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/GimmickGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/ThunderController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/ThunderController.cs.meta
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
Labels: _10

#520 【GameplayScene】竜巻初期位置の修正
  Assets/Project/Scripts/GamePlayScene/Gimmick/TornadoController.cs
  Assets/Project/Scripts/Utils/Definitions/SizeDefinitions.cs
Labels: _1

#523 拡大縮小時に道の太さを調整する
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LineController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/MenuSelectScene/ScaleContent.cs
Labels: _1

#515 総合記録画面の実装準備
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/IBottleGetDamagedHandler.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/AbstractGimmickController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/TornadoController.cs
  Assets/Project/Scripts/GamePlayScene/PauseWindow.cs
  Assets/Project/Scripts/MenuSelectScene/Settings/ResetController.cs
  Assets/Project/Scripts/StartUpScene/StartUpDirector.cs
  Assets/Project/Scripts/Utils/AppManager.cs
  Assets/Project/Scripts/Utils/AppManager.cs.meta
  Assets/Project/Scripts/Utils/Definitions/FailureReasonType.cs
  Assets/Project/Scripts/Utils/Definitions/FailureReasonType.cs.meta
  Assets/Project/Scripts/Utils/Definitions/GimmickDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickType.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickType.cs.meta
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/MyPlayerPrefs.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/RecordData.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/RecordData.cs.meta
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
  Assets/Project/Scripts/Utils/ScheduleManager.cs
  Assets/Project/Scripts/Utils/ScheduleManager.cs.meta
Labels: _8, __4

#524 デフォルトボタン押下時に，更新されない問題を解決
  Assets/Project/Scripts/MenuSelectScene/Settings/ToDefaultController.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/UserSettings.cs
Labels: _1

#525 個別記録画面の実装準備
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/Utils/AppManager.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: _1

#521 【GamePlayScene】太陽光ギミック実装
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Actors/Gimmicks/SolarBeam.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam.png
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam.png.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@attack.anim
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@attack.anim.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@idle.anim
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@idle.anim.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@in.anim
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@in.anim.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@out.anim
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@out.anim.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@warning.anim
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeam@warning.anim.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeamAC.controller
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeamAC.controller.meta
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeamPrefab.prefab
  Assets/Project/Actors/Gimmicks/SolarBeam/SolarBeamPrefab.prefab.meta
  Assets/Project/Actors/Gimmicks/Thunder/Thunder@attack.anim
  Assets/Project/Actors/Gimmicks/Thunder/Thunder@attack.anim.meta
  Assets/Project/Actors/Gimmicks/Thunder/Thunder@warning.anim
  Assets/Project/Actors/Gimmicks/Thunder/Thunder@warning.anim.meta
  Assets/Project/AddressableResources/GameDatas/Stages/Spring_1/1.asset
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/GameDatas/GimmickData.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/IBottleGetDamagedHandler.cs
  Assets/Project/Scripts/GamePlayScene/Boundary.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/GimmickGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/SolarBeamController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/SolarBeamController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Gimmick/TornadoController.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/FailureReasonType.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickType.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
Labels: _7, __4

#530 レベル選択画面背景、仮画像組み込み
  Assets/Project/Prefabs/StageSelectScene/Tree.prefab
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Textures/LevelSelectScene/Materials/road.mat
  Assets/Project/Textures/LevelSelectScene/background.png
  Assets/Project/Textures/LevelSelectScene/background.png.meta
  ProjectSettings/TagManager.asset
Labels: _7, __2
