Repository LITO-apps/Treevel-client, pull requests merged in 2020-07, with the labels that each got.

#472 ボトルの移動を連続移動にする（大幅なリファクタリング）
  Assets/AddressableAssetsData/AssetGroups/Bottles.asset
  Assets/Project/Animations/Bottles/BottleDead.anim
  Assets/Project/Animations/Bottles/BottleDead.anim.meta
  Assets/Project/Animations/Bottles/BottleGetAttacked.anim
  Assets/Project/Animations/Bottles/BottleGetAttacked.anim.meta
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/AttackableDummyBottleController.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/IBottleEnterTileHandler.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/IBottleEnterTileHandler.cs.meta
  Assets/Project/Scripts/GamePlayScene/Bottle/IBottleGetDamagedHandler.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/IBottleSuccessHandler.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/IEnterTileHandler.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/NormalBottleController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/AnimationDefinitions.cs
Labels: _9, refactoring

#481 StaticDummyBottleの仮画像組み込み
  Assets/AddressableAssetsData/AssetGroups/Bottles.asset
  Assets/Project/Prefabs/GamePlayScene/Bottle/StaticDummyBottlePrefab.prefab
  Assets/Project/Textures/GamePlayScene/Bottle/staticDummyBottle.png
  Assets/Project/Textures/GamePlayScene/Bottle/staticDummyBottle.png.meta
Labels: _1

#476 氷タイルの実装
  Assets/AddressableAssetsData/AssetGroups/Tiles.asset
  Assets/Project/AddressableResources/GameDatas/Stages/Spring_1/2.asset
  Assets/Project/Prefabs/GamePlayScene/Tile/IceTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/IceTilePrefab.prefab.meta
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Bottle/DynamicBottleController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/AbstractTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/HolyTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/IceTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/IceTileController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Tile/SpiderwebTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/TileGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TileDefinitions.cs
  Assets/Project/Scripts/Utils/Library/Extension/ExtensionVector2.cs
  Assets/Project/Textures/GamePlayScene/Tile/iceTile.png
  Assets/Project/Textures/GamePlayScene/Tile/iceTile.png.meta
Labels: _2

#475 クリア状況によってレベル選択画面の木の表示を変える
  Assets/Project/Prefabs/LevelSelectScene/LevelTree.prefab
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/IClearTreeHandler.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/IClearTreeHandler.cs.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LevelSelectDirector.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/LineController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/NumClearTreeHandler.cs.meta
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/TreeController.cs
  Assets/Project/Scripts/StageSelectScene/BranchController.cs
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/DefaultDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/PlayerPrefsKeys.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: _5

#482 Unity のバージョンを `2019.4.2f1` に上げる
  Assets/AddressableAssetsData/AddressableAssetSettings.asset
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Prefabs/Base Multi Language Text.prefab
  Assets/Project/Prefabs/Base Text.prefab
  Assets/Project/Prefabs/GamePlayScene/Background.prefab
  Assets/Project/Prefabs/GamePlayScene/Bottle/AttackableDummyBottlePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bottle/DynamicDummyBottlePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bottle/LifeBottlePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Bottle/NormalBottlePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/BulletGroupPrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Button.prefab
  Assets/Project/Prefabs/GamePlayScene/FailurePopup.prefab
  Assets/Project/Prefabs/GamePlayScene/PauseWindow.prefab
  Assets/Project/Prefabs/GamePlayScene/SuccessPopup.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/HolyTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/NormalTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/SpiderwebTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/WarpTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/TutorialWindow.prefab
  Assets/Project/Prefabs/LevelSelectScene/LevelTree.prefab
  Assets/Project/Prefabs/ProgressBar.prefab
  Assets/Project/Prefabs/RecordScene/Graph.prefab
  Assets/Project/Prefabs/RecordScene/LevelContents.prefab
  Assets/Project/Prefabs/RecordScene/SuccessLine.prefab
  Assets/Project/Prefabs/StageSelectScene/BackButton.prefab
  Assets/Project/Prefabs/StageSelectScene/Branch.prefab
  Assets/Project/Prefabs/StageSelectScene/Gimmick Overview.prefab
  Assets/Project/Prefabs/StageSelectScene/LeftButton.prefab
  Assets/Project/Prefabs/StageSelectScene/Loading.prefab
  Assets/Project/Prefabs/StageSelectScene/LoadingBackground.prefab
  Assets/Project/Prefabs/StageSelectScene/OverviewPopup.prefab
  Assets/Project/Prefabs/StageSelectScene/RightButton.prefab
  Assets/Project/Prefabs/StageSelectScene/Stage.prefab
  Assets/Project/Prefabs/StageSelectScene/Tree.prefab
  Assets/Project/Prefabs/StageSelectScene/TreeName.prefab
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutomnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity
  Assets/Project/Scenes/StartUpScene.unity
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/DeviceSimulatorSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/ProjectVersion.txt
  README.md
Labels: _1

#489 【ステージ選択画面】木の間の遷移実装
  Assets/Project/Scripts/StageSelectScene/StageSelectDirector.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs
Labels: _3

#490 StageDataがリセットされていない問題の修正
  Assets/Project/Scripts/StageSelectScene/BranchController.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/StageStatus.cs
Labels: _1
