Repository LITO-apps/Treevel-client, pull requests merged in 2020-09, with the labels that each got.

#533 Audio共通化処理
  Assets/Project/Actors/Common.meta
  Assets/Project/Actors/Common/SoundManager.prefab
  Assets/Project/Actors/Common/SoundManager.prefab.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/GamePlayScene.unity
  Assets/Project/Scenes/StartUpScene.unity
  Assets/Project/Scripts/GamePlayScene/Bottle/AbstractBottleController.cs
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/ThunderController.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/ErrorDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TextDefinitions.cs
  Assets/Project/Scripts/Utils/PlayerPrefsUtils/UserSettings.cs
  Assets/Project/Scripts/Utils/SoundManager.cs
  Assets/Project/Scripts/Utils/SoundManager.cs.meta
Labels: _6

#539 【GamePlayScene】ゲーム開始時特殊タイルを削除する
  Assets/Project/Scripts/GamePlayScene/GamePlayDirector.cs
Labels: _1

#543 道(と枝)の描画順序を整える
  Assets/Project/Prefabs/StageSelectScene/Tree.prefab
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutomnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SpringStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/SummerStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/WinterStageSelectScene.unity
  Assets/Project/Scripts/MenuSelectScene/LevelSelect/RoadController.cs
  Assets/Project/Scripts/StageSelectScene/BranchController.cs
  Assets/Project/Scripts/Utils/SynchronizeCanvasObject.cs
  Assets/Project/Scripts/Utils/SynchronizeCanvasObject.cs.meta
  Assets/Project/Textures/LevelSelectScene/Materials/road.mat
  Assets/Project/Textures/StageSelectScene/Materials/branch.mat
Labels: _5, __1

#535 【GamePlaytScene】突風ギミック
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Actors/Gimmicks/GustWind.meta
  Assets/Project/Actors/Gimmicks/GustWind/GustWind.png
  Assets/Project/Actors/Gimmicks/GustWind/GustWind.png.meta
  Assets/Project/Actors/Gimmicks/GustWind/GustWind@attack.anim
  Assets/Project/Actors/Gimmicks/GustWind/GustWind@attack.anim.meta
  Assets/Project/Actors/Gimmicks/GustWind/GustWind@warning.anim
  Assets/Project/Actors/Gimmicks/GustWind/GustWind@warning.anim.meta
  Assets/Project/Actors/Gimmicks/GustWind/GustWindAC.controller
  Assets/Project/Actors/Gimmicks/GustWind/GustWindAC.controller.meta
  Assets/Project/Actors/Gimmicks/GustWind/GustWindPrefab.prefab
  Assets/Project/Actors/Gimmicks/GustWind/GustWindPrefab.prefab.meta
  Assets/Project/Actors/Gimmicks/GustWind/GustWindWarning.png
  Assets/Project/Actors/Gimmicks/GustWind/GustWindWarning.png.meta
  Assets/Project/AddressableResources/GameDatas/Stages/Spring_1/1.asset
  Assets/Project/AddressableResources/GameDatas/Stages/Summer_1/2.asset
  Assets/Project/AddressableResources/GameDatas/Stages/Summer_1/3.asset
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/GameDatas/GimmickData.cs
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/GimmickGenerator.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/GustWindController.cs.meta
  Assets/Project/Scripts/GamePlayScene/Gimmick/SolarBeamController.cs
  Assets/Project/Scripts/GamePlayScene/Gimmick/TornadoController.cs
  Assets/Project/Scripts/Utils/AddressableAssetManager.cs
  Assets/Project/Scripts/Utils/Definitions/FailureReasonType.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickDirection.cs
  Assets/Project/Scripts/Utils/Definitions/GimmickDirection.cs.meta
  Assets/Project/Scripts/Utils/Definitions/GimmickType.cs
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Library/GimmickLibrary.cs
Labels: _10, _8

#553 Automn → Autumn
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutumnStageSelectScene.unity
  Assets/Project/Scenes/StageSelectScene/AutumnStageSelectScene.unity.meta
  Assets/Project/Scripts/Utils/Definitions/StringDefinitions.cs
  Assets/Project/Scripts/Utils/Definitions/TreeDefinitions.cs
  Assets/Project/Scripts/Utils/Library/TreeLibrary.cs
  Assets/Project/Textures/LevelSelectScene/autumn1.png
  Assets/Project/Textures/LevelSelectScene/autumn1.png.meta
  Assets/Project/Textures/LevelSelectScene/autumn2.png
  Assets/Project/Textures/LevelSelectScene/autumn2.png.meta
  Assets/Project/Textures/LevelSelectScene/autumn3.png
  Assets/Project/Textures/LevelSelectScene/autumn3.png.meta
Labels: _1

#548 ワープする際ボトルが大きくなる問題を修正
  Assets/Project/Actors/Tiles.meta
  Assets/Project/Actors/Tiles/WarpTile.meta
  Assets/Project/Actors/Tiles/WarpTile/WarpTile@bottle_in.anim
  Assets/Project/Actors/Tiles/WarpTile/WarpTile@bottle_in.anim.meta
  Assets/Project/Actors/Tiles/WarpTile/WarpTile@bottle_out.anim
  Assets/Project/Actors/Tiles/WarpTile/WarpTile@bottle_out.anim.meta
  Assets/Project/Actors/Tiles/WarpTile/WarpTileAC.controller
  Assets/Project/Actors/Tiles/WarpTile/WarpTileAC.controller.meta
  Assets/Project/Actors/Tiles/WarpTile/WarpTileEffect@idle.anim
  Assets/Project/Actors/Tiles/WarpTile/WarpTileEffect@idle.anim.meta
  Assets/Project/Actors/Tiles/WarpTile/WarpTilePrefab.prefab
  Assets/Project/Actors/Tiles/WarpTile/WarpTilePrefab.prefab.meta
  Assets/Project/Animations/Tiles/warpTileEffect.controller
  Assets/Project/Prefabs/GamePlayScene/Bottle/NormalBottlePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/HolyTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/IceTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/NormalTilePrefab.prefab
  Assets/Project/Prefabs/GamePlayScene/Tile/SpiderwebTilePrefab.prefab
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Tile/AbstractTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
Labels: _3

#552 初期配置時に `OnBottleEnter()` を呼び出す
  Assets/Project/Scripts/GamePlayScene/BoardManager.cs
  Assets/Project/Scripts/GamePlayScene/Tile/AbstractTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/HolyTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/IceTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/NormalTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/SpiderwebTileController.cs
  Assets/Project/Scripts/GamePlayScene/Tile/WarpTileController.cs
Labels: _1, __1
