Repository LITO-apps/Treevel-client, pull requests merged in 2020-12, with the labels that each got.

#627 汎用メッセージダイアログ
  Assets/AddressableAssetsData/AssetGroups/Default Local Group.asset
  Assets/Project/Actors/UIs/Common/ErrorMessageBox.prefab
  Assets/Project/Actors/UIs/Common/MessageDialog.prefab
  Assets/Project/Actors/UIs/Common/MessageDialog.prefab.meta
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scenes/StartUpScene.unity
  Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs
  Assets/Project/Scripts/Common/Components/UIs/MessageDialog.cs.meta
  Assets/Project/Scripts/Common/Entities/TextIndex.cs
  Assets/Project/Scripts/Common/Managers/UIManager.cs
Labels: _4

#634 EDirectionを0から数える
  Assets/Project/GameDatas/Stages/Spring_1/1.asset
  Assets/Project/GameDatas/Stages/Spring_1/10.asset
  Assets/Project/GameDatas/Stages/Spring_1/2.asset
  Assets/Project/GameDatas/Stages/Spring_1/3.asset
  Assets/Project/GameDatas/Stages/Spring_1/4.asset
  Assets/Project/GameDatas/Stages/Spring_1/5.asset
  Assets/Project/GameDatas/Stages/Spring_1/6.asset
  Assets/Project/GameDatas/Stages/Spring_1/7.asset
  Assets/Project/GameDatas/Stages/Spring_1/8.asset
  Assets/Project/GameDatas/Stages/Spring_1/9.asset
  Assets/Project/GameDatas/Stages/Spring_2/1.asset
  Assets/Project/GameDatas/Stages/Spring_2/2.asset
  Assets/Project/GameDatas/Stages/Spring_2/3.asset
  Assets/Project/GameDatas/Stages/Spring_2/4.asset
  Assets/Project/GameDatas/Stages/Spring_2/5.asset
  Assets/Project/GameDatas/Stages/Spring_3/1.asset
  Assets/Project/GameDatas/Stages/Summer_1/2.asset
  Assets/Project/GameDatas/Stages/Summer_1/3.asset
  Assets/Project/Scripts/Common/Entities/Direction.cs
  Assets/Project/Scripts/Editor/StageDataEditor.cs
  Assets/Project/Scripts/Modules/GamePlayScene/Gimmick/TornadoController.cs
Labels: _1

#635 データリセットする際警告を出す
  Assets/Project/Resources/GameDatas/translation.csv
  Assets/Project/Scripts/Common/Entities/TextIndex.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Settings/ResetController.cs
Labels: _1

#671 【UniRx】StartUpScene
  Assets/Project/Scripts/Common/Managers/GameDataManager.cs
  Assets/Project/Scripts/Common/Managers/UIManager.cs
  Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
Labels: _2

#675 fix UIManager initialization
  Assets/Project/Scripts/Common/Managers/UIManager.cs
  Assets/Project/Scripts/Modules/StartUpScene/StartUpDirector.cs
Labels: _1, bug

#673 個別記録画面を、すべての季節・木に拡張する
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/IndividualRecord.prefab
  Assets/Project/Actors/UIs/MenuSelectScene/Record/Individual/IndividualRecord.prefab.meta
  Assets/Project/Scenes/MenuSelectScene.unity
  Assets/Project/Scripts/Common/Entities/SeasonId.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/IndividualRecordDirector.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs
  Assets/Project/Scripts/Modules/MenuSelectScene/Record/SeasonSelectButton.cs.meta
Labels: _8
